### ISSUE TITLE
[4.0.0] `implicitComponents` in conjunction with a custom `componentName` pattern causes error

### ISSUE THREAD

**Issue by kulmajaba** [postcss/postcss-bem-linter#174]
As the title states, you get an error on 4.0.0 using both `implicitComponents` and `componentName` in the config:

```
TypeError: componentNamePattern.test is not a function
    at module.exports (<path>/node_modules/postcss-bem-linter/lib/get-component-name-from-filename.js:11:28)
    at findRanges (<path>/node_modules/postcss-bem-linter/index.js:125:25)
    at Object.Once (<path>/node_modules/postcss-bem-linter/index.js:43:22)
    at LazyResult.runOnRoot (<path>/node_modules/postcss/lib/lazy-result.js:355:23)
    at LazyResult.runAsync (<path>/node_modules/postcss/lib/lazy-result.js:286:26)
    at LazyResult.async (<path>/node_modules/postcss/lib/lazy-result.js:160:30)
    at LazyResult.then (<path>/node_modules/postcss/lib/lazy-result.js:436:17)
    at file://<path>/node_modules/postcss-cli/index.js:255:10
    at async Promise.all (index 0)
```

When using a custom `componentName` pattern in the postcss-bem-linter config, `lib/get-component-name-from-filename.js` has been documented to receive `componentNamePattern` as string, but actually expects it to be a testable RegExp.

`lib/generate-config.js` provides the `componentNamePattern` at line 65. Changing the line to generate a RegExp fixes the error:
```diff
- componentNamePattern: patterns.componentName || /^[-_a-zA-Z0-9]+$/,
+ componentNamePattern: patterns.componentName ? new RegExp(patterns.componentName) : /^[-_a-zA-Z0-9]+$/,
```

Not using `implicitComponents` or not defining a `componentName` pattern will also cause the error to not occur.

Minimal repro: https://github.com/kulmajaba/postcss-bem-4-repro

If the proposed fix seems to be correct I can provide a PR if necessary :)

**Comment by simonsmith** [comment]
Hey @kulmajaba, I'd definitely welcome a fix if you would like. Do you think there a test we can add to validate the bug first, and then have your suggested change pass it?

**Comment by kulmajaba** [comment]
I think so, I took a quick look at the selector-validation tests and it should be doable. How do you want to handle this? I could open a WIP PR first with just the failing test, we can verify the fail, and then add the fix?
